### ISSUE TITLE
Throw error & crash module: scaleBorder not registered setting

### ISSUE THREAD

**Issue by devinterx** [p4535992/token-factions#1]
https://github.com/p4535992/token-factions/blob/7c9c7cb945bdbbd54ef13f9260713ff928cebc7a/src/module/tokenFactions.ts#L791

**Comment by devinterx** [comment]
i'm temporary set sB = 1; & it works

**Comment by ravingdragoon** [comment]
> i'm temporary set sB = 1; & it works

So changing line 791 to "const sB = 1 getGame().settings.get(TOKEN_FACTIONS_MODULE_NAME, 'scaleBorder');" fixes the issue?

**Comment by p4535992** [comment]
my god is there anyone other than me who uses this module? I thought I was the only one! Thanks for the feedback.
Try out the version 0.2.11 and let me know. Sorry for th trouble.
