### ISSUE TITLE
[BUG] "Circular Borders" doesn't scale with "Scale Borders"

### ISSUE THREAD

**Issue by King-Wedgie** [p4535992/token-factions#13]
**Module Version:** v0.2.18

**Describe the bug:**
*Title*

**Screenshots:**
![image](https://user-images.githubusercontent.com/73143074/165590810-9dab6565-3b9f-49f3-a357-b3af2dc9ce85.png)

**Browser:**
 Verified in Foundry VTT dedicated, Firefox, and Chrome

**Foundry Version:** v9.269

**Game System:** DnD5e 1.5.7

**Additional context:**
Is bugged with or without other modules.

**Comment by p4535992** [comment]
Should be fixed with 0.2.19
