### ISSUE TITLE
No Configuration settings[BUG]

### ISSUE THREAD

**Issue by CasualTerror** [p4535992/token-factions#16]
**Foundry Version:** Version 9

**Game System:** D&D5e 1.6.3

I installed the module and nothing. It's like I didn't install it other than my module count went up and there's an option to check it in manage module. I tried it with only token faction and libwrapper on and there weren't any options to do anything. what am I missing?

**Comment by CepheiA2** [comment]
Same, token factions options and functionality disappeared

**Comment by p4535992** [comment]
it shoul be solved
