### ISSUE TITLE
[BUG] Token borders disappear when changes are made to a token

### ISSUE THREAD

**Issue by amcvfx** [p4535992/token-factions#2]
**Module Version:** v0.2.15

**Describe the bug**
Whenever changes are made to a token, i.e. Vision, Resource bars or nameplate the token border disappears from the token. This was an issue with the previous version, before it was forked, as well.

**Foundry Version:** 
0.8.9

**Game System:** 
D&D 5th

**Comment by p4535992** [comment]
should be solved from [Recreate destroyed factions container](https://github.com/p4535992/token-factions/pull/10) ty for the contribution, i will put in the next release

**Comment by p4535992** [comment]
Should be fixed on 0.2.17
