### ISSUE TITLE
Colored Rings disappear when changing map[BUG]

### ISSUE THREAD

**Issue by Strandigel85** [p4535992/token-factions#5]
**Module Version:** v0.0.0

**Describe the bug**
When I start a campaign no actors have rings, after i hover over one creature the rings appear. As soon as I change the map all rings disappear and they only reappear when I close the campaign and open it again. Tested on two different systems with a clean reinstallation of foundry and only Token Factions is installed.

**Foundry Version:** 
9.249
**Game System:** 
dnd5

**Comment by p4535992** [comment]
should be solved from [Recreate destroyed factions container](https://github.com/p4535992/token-factions/pull/10) ty for the contribution, i will put in the next release
